### ISSUE TITLE
[Question] How to target attribute selector with typescript & react bindings

### ISSUE THREAD

**Issue by MathiasAnderssonKnowit** [frenic/glitz#11]
Hi,

We would like to target attribute selectors when using react bindings and typescript. I saw the "selector" method in the readme for unknown properties, but it doesn't seem to be available in the react bindings? https://github.com/frenic/glitz#unknown-properties

If we were to solve it using custom properties, how would that look? I have tested the example at https://github.com/frenic/glitz#add-custom-properties but cannot seem to add/find any custom properties.

How else could we solve this and what would you recommend?

**Comment by MathiasAnderssonKnowit** [comment]
Ping

**Comment by frenic** [comment]
I don't quite follow you. You would like to do something like `styled.div({ '[type="button"]': { backgroundColor: 'red' } })`? Which version of Glitz are you using?

**Comment by MathiasAnderssonKnowit** [comment]
Yes correctly, I'm are using "@glitz/react": "3.1.3" along with typescript. When I try to write something similar to your example I get the following error: 
Object literal may only specify known properties, and ''[type="button"]'' does not exist in type 'Style'

**Comment by frenic** [comment]
Version 3.1.3 doesn't support attribute selectors. I believe you're reading the readme for the next major release which has support for attribute selectors. This is the [readme for you version](https://github.com/frenic/glitz/blob/%40glitz/react%403.1.3/README.md). I plan to release v4 @glitz/react this week. You can upgrade using the `next` tag now if you'd like, but there's no complete changelog I can provide you at this moment and the readme is not fully updated.

```
"@glitz/core": "next",
"@glitz/react": "next",
"@glitz/transformers": "next",
```

**Comment by frenic** [comment]
I have to warn you there's quite some major changes unfortunately. The most major change is that `props.compose()` is removed because Glitz v4 will compose automatically to the closest Glitz element.

So this has to be changed:
```tsx
import { styled } from '$glitz/react';

// v3
function InnerComponent(props) {
  return <styled.Div css={props.compose()}>;
}

// v4-alpha
function InnerComponent(props) {
  return <styled.Div />;
}

// v4-alpha alt
import { forwardStyle } from '$glitz/react';
const InnerComponent = forwardStyle(props => {
  return <styled.Div css={props.compose()}>;
})

const StyledComponent = styled(InnerComponent, { color: 'red' });

**Comment by MathiasAnderssonKnowit** [comment]
I see, thank you!
I will update to the next version and we'll see what breaks. We would have to update anyhow to keep things up to date. :) 

Could I otherwise fix this with custom properties, and how would that look like? How would I inject the custom properties to the default styled object from @glitz/react?

**Comment by frenic** [comment]
I don't know how you could fix this with CSS Custom Properties. But I guess this is a hack that might work:

```ts
import { pseudo } from '$glitz/core';
import { styled } from '$glitz/react';

styled.div(pseudo(':nth-child(n)[type="button"]', { backgroundColor: 'red' }))
```

**Comment by MathiasAnderssonKnowit** [comment]
I was thinking about the custom properties explained here, could that solve it?

Otherwise your example might work fine. Thanks!

https://github.com/frenic/glitz/blob/%40glitz/react%403.1.3/README.md#add-custom-properties

**Comment by frenic** [comment]
That can't help you with solving attribute selectors I'm afraid

**Comment by MathiasAnderssonKnowit** [comment]
Alright, well the pseudo hack worked and we'll try to update to the next version as well. So thank you for the support!
