### ISSUE TITLE
Message: null is not an object (evaluating 'n.cssRules')

### ISSUE THREAD

**Issue by dennisek** [frenic/glitz#7]
Hey!

getting some null errors:

![image](https://user-images.githubusercontent.com/54796561/68599788-82449580-04a1-11ea-8284-ac9d1e09e827.png)

Error occured in Safari and Mobile Safari

**Comment by frenic** [comment]
This is weird 🤔 The only way I'm able to reproduce this is if the element isn't mounted to the DOM.

```js
const style = document.createElement('style');
console.log(style.sheet); // -> null

document.head.append(style);
console.log(style.sheet); // -> CSSStyleSheet 

document.head.removeChild(style)
console.log(style.sheet); // -> null
```
