### ISSUE TITLE
Missing webkit specific pseudo elements

### ISSUE THREAD

**Issue by MathiasAnderssonKnowit** [frenic/glitz#9]
Hi!

For the react bindings lib with typescript I cannot see that we have the following webkit specific pseudo elements typed:
::-webkit-outer-spin-button
::-webkit-inner-spin-button

Is this something that can be added, or is there any other way to target this?

**Comment by frenic** [comment]
You can try this

```tsx
import { pseudo } from '@glitz/core';
import { styled } from '@glitz/react';

const NumberInput = styled.input({
  /* style */
  ...pseudo(['::-webkit-outer-spin-button', '::-webkit-outer-spin-button'], {
    /* psudeo style */
  }),
});

```

**Comment by MathiasAnderssonKnowit** [comment]
Right, forgot about the pseudo function.

Thanks!
